export default `Araria (Lok Sabha constituency)
Arrah (Lok Sabha constituency)
Aurangabad (Bihar Lok Sabha constituency)
Bagaha (Lok Sabha constituency)
Balia, Bihar (Lok Sabha constituency)
Banka (Lok Sabha constituency)
Barh (Lok Sabha constituency)
Begusarai (Lok Sabha constituency)
Bettiah (Lok Sabha constituency)
Bhagalpur (Lok Sabha constituency)
Bikramganj (Lok Sabha constituency)
Buxar (Lok Sabha constituency)
Chapra (Lok Sabha constituency)
Darbhanga (Lok Sabha constituency)
Gaya (Lok Sabha constituency)
Gopalganj (Lok Sabha constituency)
Hajipur (Lok Sabha constituency)
Jahanabad (Lok Sabha constituency)
Jamui (Lok Sabha constituency)
Jhanjharpur (Lok Sabha constituency)
Karakat (Lok Sabha constituency)
Katihar (Lok Sabha constituency)
Kesariya (Lok Sabha constituency)
Khagaria (Lok Sabha constituency)
Kishanganj (Lok Sabha constituency)
Madhepura (Lok Sabha constituency)
Madhubani (Lok Sabha constituency)
Maharajganj (Bihar Lok Sabha constituency)
Motihari (Lok Sabha constituency)
Munger (Lok Sabha constituency)
Muzaffarpur (Lok Sabha constituency)
Nalanda (Lok Sabha constituency)
Nawada (Lok Sabha constituency)
Paschim Champaran (Lok Sabha constituency)
Pataliputra (Lok Sabha constituency)
Patna (Lok Sabha constituency)
Patna Sahib (Lok Sabha constituency)
Purnia (Lok Sabha constituency)
Purvi Champaran (Lok Sabha constituency)
Rosera (Lok Sabha constituency)
Saharsa (Lok Sabha constituency)
Samastipur (Lok Sabha constituency)
Saran (Lok Sabha constituency)
Sasaram (Lok Sabha constituency)
Sheohar (Lok Sabha constituency)
Sitamarhi (Lok Sabha constituency)
Siwan (Lok Sabha constituency)
Supaul (Lok Sabha constituency)
Ujiarpur (Lok Sabha constituency)
Vaishali (Lok Sabha constituency)
Valmiki Nagar (Lok Sabha constituency)`.split('\n');